### ISSUE TITLE
Problem in Send Heros to work while perform just 1 Scroll

### ISSUE THREAD

**Issue by Thugawa** [afkapp/bombcrypto-bcbot#5]
Hi, first of all sorry about my english, so i found a problem and a solution that i think need to put in this project, when you set a Scroll attemp as 1 the bot put the heros to work, peform a scroll and don't send the other heroes, the simple way to fix it is put '=' in the fuction getMoreHeroes, have a good new year and thanks for the awesome project.

while (empty_scrolls_attempts >= 0):

**Comment by afkapp** [comment]
Hello,

Don't worry for the english. Your english is good.

Greater than or equal to zero, it means always, since we don't work with negative numbers, and in this case a function (while) would not be necessary.

The proposed solution would result in a bug, which for this reason this (while) was added.

The problem there is another, and always related to adjust the config.yaml.

Thank you, happy new year!
